### ISSUE TITLE
Support for Ultima 4.x xml files

### ISSUE THREAD

**Issue by BSchilperoort** [bdestombe/python-dts-calibration#4]
Add support for older software versions of the Ultima-DTS (specifically v4.x)

**Comment by bdestombe** [comment]
Hi Bart, could you maybe add a couple of 4.x files to the `tests/data/` directory?

**Comment by BSchilperoort** [comment]
> Hi @BSchilperoort , could you maybe add a couple of 4.x files to the `tests/data/` directory?
Done

**Comment by BSchilperoort** [comment]
Fixed with #12
