### ISSUE TITLE
Export to netCDF fails when Silixa xml files do not have a configuration description

### ISSUE THREAD

**Issue by BSchilperoort** [bdestombe/python-dts-calibration#8]
**Describe the bug**
Export of a calibrated dataset to netCDF fails on an attribute. "TypeError: Invalid value for attr: None must be a number string, ndarray or a list/tuple of numbers/strings for serialization to netCDF files".

**To Reproduce**
1. Have a Silixa xml file without anything in the configuration description "<ConfigurationComment>"
2. Load the xml files
3. Attempt to export to netcdf

**Expected behavior**
'None' types should be replaced with an empty string, to allow export of dataset.

**Comment by BSchilperoort** [comment]
It would probably be good to check all attrs if they follow the valid types/are not _None_, or any other invalid types.

xarray's check is in the _'_validate_attrs(dataset)'_ function of _'xarray\backends\api.py'_

**Comment by BSchilperoort** [comment]
The following code should work (to be run before returning the read dataset).




```python
for attribute, value in ds.attrs.items(): 
    if value is None:  
        ds.attrs[attribute] = ''
```

**Comment by bdestombe** [comment]
Hi Bart, I added your fix to the `to_netcdf` function. Thanks!
